server.port=8085
server.servlet.context-path=/springboot-boilerplate
oracle.jdbc.level=OFF

spring.datasource.url=jdbc:oracle:thin:@localhost:1522/freepdb1
spring.datasource.username=system
spring.datasource.password=test_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
